name: shellspec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow this workflow to be executed manually from the Actions tab:
  workflow_dispatch:

jobs:
  shellspec:
    name: shellspec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s -- --yes
      - name: run shellspec using bash
        run: bash shellspec --pattern '*.spec' spec
