name: 'shellcheck'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow this workflow to be executed manually from the Actions tab:
  workflow_dispatch:

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: run shellcheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
        with:
         ignore_paths: spec
