name: 'shellcheck'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow this workflow to be executed manually from the Actions tab:
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
       ignore: './spec'
